### ISSUE TITLE
401 API issue D2RW

### ISSUE THREAD

**Issue by tnguyen1337** [Synse/dclone-discord#15]
I was able to replace all the config sections and have the bot set up. It auths to discord, it auth posts terror data in chat. It seems to be failing on Planned-Walks function.

```
:/home/d2r_notifications/d2r-discord-bot# python3 d2r-discord-bot.py
Tracking DClone for All Regions, Ladder, Hardcore
2023-10-11 16:18:49 INFO     discord.client logging in using static token
2023-10-11 16:18:49 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: f4d141b7c9d8f7a4d7600a18b2992c59).
Bot logged into Discord as "D2R-Intel-Bot#3074"
Connected to 1 servers: We Met on E-Harmony
Messages will be sent to #diablo-ii on the We Met on E-Harmony server
[PlannedWalk] D2RuneWizard API Error: 401 Client Error: Unauthorized for url: https://d2runewizard.com/api/diablo-clone-progress/planned-walks?token=<<TOKEN>>
````

verified through postman and via http the token is working just fine so something about the passing of the function is failing. Weird because the other part of the function uses the same token and the auth passes.

**Comment by Synse** [comment]
@tnguyen1337 do you have the `DCLONE_D2RW_CONTACT` environment variable set to your *email address*? This has to be set to your D2RW account email or it will fail with the error above.

I can add a check to make sure the value looks like an email.

**Comment by Synse** [comment]
@tnguyen1337 I pushed an updated version that checks if `DCLONE_D2RW_CONTACT` looks like an email address and disables the D2RuneWizard bits if not. Give that a try and let me know if that helps or not.

**Comment by Synse** [comment]
@tnguyen1337 have you had a chance to check your `DCLONE_d2RW_CONTACT` is an email with the latest version?
