### ISSUE TITLE
can't start dcclone

### ISSUE THREAD

**Issue by Dalk2ness** [Synse/dclone-discord#17]
i only show up " Please set DCLONE_DISCORD_TOKEN and DCLONE_DISCORD_CHANNEL_ID in your environment. "

![image](https://github.com/user-attachments/assets/c30071b4-96b2-4266-91cd-e8a72f3abc47)

**Comment by Synse** [comment]
@Dalk2ness the [`environ.get('...')` lines](https://www.geeksforgeeks.org/python-os-environ-object/#:~:text=Retrieving%20Specific%20Environment%20Variables%20Using%20os.environ%20Object) read the values from an environment variable.

So you should set the values entered into the file as the `DCLONE_DISCORD_TOKEN` and `DCLONE_DISCORD_CHANNEL_ID` as environment variables (and revert the changes you made). Alternatively you can change the lines to:

```py3
DCLONE_DISCORD_TOKEN = "12921..."
DCLONE_DISCORD_CHANNEL_ID = int("6723...")
```

where the `"12921..."` and `"6723..."` values the full value (redacted in your screenshot above).

**Comment by Synse** [comment]
Added some clarification in 0b645b8 that should prevent this confusion going forward.
