### ISSUE TITLE
Feature request for more env settings

### ISSUE THREAD

**Issue by Meanski** [Synse/dclone-discord#3]
It would be neat to be able to set some further env settings for things like HC/SC/ALL and the servers/regions you'd like to see updates from :) awesome otherwise!

**Comment by Synse** [comment]
Hey @Meanski those environment variables (`DCLONE_REGION`, `DCLONE_LADDER`, and `DCLONE_HC`) already exist and are documented [here](https://github.com/Synse/dclone-discord#configuration).

So if you want hardcore ladder and non-ladder all regions you could run `DCLONE_LADDER=1 DCLONE_HC= ./dclone-discord.py` (or `export DCLONE_LADDER=1; export DCLONE_HC=; python3 dclone-discord.py`. Note that `DCLONE_HC=` is correct as it sets a _blank_/empty value, which means hardcore _and_ softcore.

For Asia only softcore non-ladder you'd use `DCLONE_REGION=3 DCLONE_LADDER=2 DCLONE_HC=2 ./dclone-discord.py`, etc.

Note that `DCLONE_LADDER` and `DCLONE_HC` are not booleans, but they are the `1`, `2`, or _blank_ values used by the API documented [here](https://diablo2.io/forums/diablo-clone-uber-diablo-tracker-public-api-t906872.html).

Are there other configurations you'd like to set via environment variables?

**Comment by Meanski** [comment]
Well that is embarrassing, I must have been half asleep and did not scroll down 😅 

Thanks for that. I don't think there is anything else, I'll feedback anything more if I do!

Only other change I made was to send the updates as an embed post rather than just text, personal preference I guess: 
`
msg = self.dclone_tracker.text(region=region, ladder=ladder, hardcore=hardcore)
embed = discord.Embed(title="Uber Diablo update", description="{0}".format(msg), color=0x752421)
embed.set_footer(text="Data courtesy of diablo2.io • Created by Someone")
`
